//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApliciacionInventario.ProxyHangar {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HangarBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Inventario")]
    [System.SerializableAttribute()]
    public partial class HangarBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short activoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string areaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short equipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fec_ult_modificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string marcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_activoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string obsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short pisoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usu_registroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usu_ult_modificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Registro {
            get {
                return this.Fec_RegistroField;
            }
            set {
                if ((this.Fec_RegistroField.Equals(value) != true)) {
                    this.Fec_RegistroField = value;
                    this.RaisePropertyChanged("Fec_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short activo {
            get {
                return this.activoField;
            }
            set {
                if ((this.activoField.Equals(value) != true)) {
                    this.activoField = value;
                    this.RaisePropertyChanged("activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string area {
            get {
                return this.areaField;
            }
            set {
                if ((object.ReferenceEquals(this.areaField, value) != true)) {
                    this.areaField = value;
                    this.RaisePropertyChanged("area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short equipo {
            get {
                return this.equipoField;
            }
            set {
                if ((this.equipoField.Equals(value) != true)) {
                    this.equipoField = value;
                    this.RaisePropertyChanged("equipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fec_ult_modificacion {
            get {
                return this.fec_ult_modificacionField;
            }
            set {
                if ((this.fec_ult_modificacionField.Equals(value) != true)) {
                    this.fec_ult_modificacionField = value;
                    this.RaisePropertyChanged("fec_ult_modificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imagen {
            get {
                return this.imagenField;
            }
            set {
                if ((object.ReferenceEquals(this.imagenField, value) != true)) {
                    this.imagenField = value;
                    this.RaisePropertyChanged("imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                if ((object.ReferenceEquals(this.marcaField, value) != true)) {
                    this.marcaField = value;
                    this.RaisePropertyChanged("marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                if ((object.ReferenceEquals(this.modeloField, value) != true)) {
                    this.modeloField = value;
                    this.RaisePropertyChanged("modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_activo {
            get {
                return this.nom_activoField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_activoField, value) != true)) {
                    this.nom_activoField = value;
                    this.RaisePropertyChanged("nom_activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string obs {
            get {
                return this.obsField;
            }
            set {
                if ((object.ReferenceEquals(this.obsField, value) != true)) {
                    this.obsField = value;
                    this.RaisePropertyChanged("obs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short piso {
            get {
                return this.pisoField;
            }
            set {
                if ((this.pisoField.Equals(value) != true)) {
                    this.pisoField = value;
                    this.RaisePropertyChanged("piso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoField, value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usu_registro {
            get {
                return this.usu_registroField;
            }
            set {
                if ((object.ReferenceEquals(this.usu_registroField, value) != true)) {
                    this.usu_registroField = value;
                    this.RaisePropertyChanged("usu_registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usu_ult_modificacion {
            get {
                return this.usu_ult_modificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.usu_ult_modificacionField, value) != true)) {
                    this.usu_ult_modificacionField = value;
                    this.RaisePropertyChanged("usu_ult_modificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyHangar.IServiceHangar")]
    public interface IServiceHangar {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHangar/ConsultarHangar", ReplyAction="http://tempuri.org/IServiceHangar/ConsultarHangarResponse")]
        ApliciacionInventario.ProxyHangar.HangarBE ConsultarHangar(short id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHangar/ConsultarHangar", ReplyAction="http://tempuri.org/IServiceHangar/ConsultarHangarResponse")]
        System.Threading.Tasks.Task<ApliciacionInventario.ProxyHangar.HangarBE> ConsultarHangarAsync(short id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHangar/ConsultarHangar2", ReplyAction="http://tempuri.org/IServiceHangar/ConsultarHangar2Response")]
        ApliciacionInventario.ProxyHangar.HangarBE ConsultarHangar2(short id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHangar/ConsultarHangar2", ReplyAction="http://tempuri.org/IServiceHangar/ConsultarHangar2Response")]
        System.Threading.Tasks.Task<ApliciacionInventario.ProxyHangar.HangarBE> ConsultarHangar2Async(short id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHangar/ListarHangar", ReplyAction="http://tempuri.org/IServiceHangar/ListarHangarResponse")]
        ApliciacionInventario.ProxyHangar.HangarBE[] ListarHangar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHangar/ListarHangar", ReplyAction="http://tempuri.org/IServiceHangar/ListarHangarResponse")]
        System.Threading.Tasks.Task<ApliciacionInventario.ProxyHangar.HangarBE[]> ListarHangarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHangar/ListarHangar2", ReplyAction="http://tempuri.org/IServiceHangar/ListarHangar2Response")]
        ApliciacionInventario.ProxyHangar.HangarBE[] ListarHangar2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHangar/ListarHangar2", ReplyAction="http://tempuri.org/IServiceHangar/ListarHangar2Response")]
        System.Threading.Tasks.Task<ApliciacionInventario.ProxyHangar.HangarBE[]> ListarHangar2Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHangar/InsertarHangar", ReplyAction="http://tempuri.org/IServiceHangar/InsertarHangarResponse")]
        bool InsertarHangar(ApliciacionInventario.ProxyHangar.HangarBE objHangarBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHangar/InsertarHangar", ReplyAction="http://tempuri.org/IServiceHangar/InsertarHangarResponse")]
        System.Threading.Tasks.Task<bool> InsertarHangarAsync(ApliciacionInventario.ProxyHangar.HangarBE objHangarBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHangar/ActualizarHangar", ReplyAction="http://tempuri.org/IServiceHangar/ActualizarHangarResponse")]
        bool ActualizarHangar(ApliciacionInventario.ProxyHangar.HangarBE objHangarBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHangar/ActualizarHangar", ReplyAction="http://tempuri.org/IServiceHangar/ActualizarHangarResponse")]
        System.Threading.Tasks.Task<bool> ActualizarHangarAsync(ApliciacionInventario.ProxyHangar.HangarBE objHangarBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHangar/EliminarHangar", ReplyAction="http://tempuri.org/IServiceHangar/EliminarHangarResponse")]
        bool EliminarHangar(short id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHangar/EliminarHangar", ReplyAction="http://tempuri.org/IServiceHangar/EliminarHangarResponse")]
        System.Threading.Tasks.Task<bool> EliminarHangarAsync(short id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceHangarChannel : ApliciacionInventario.ProxyHangar.IServiceHangar, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceHangarClient : System.ServiceModel.ClientBase<ApliciacionInventario.ProxyHangar.IServiceHangar>, ApliciacionInventario.ProxyHangar.IServiceHangar {
        
        public ServiceHangarClient() {
        }
        
        public ServiceHangarClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceHangarClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHangarClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHangarClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ApliciacionInventario.ProxyHangar.HangarBE ConsultarHangar(short id) {
            return base.Channel.ConsultarHangar(id);
        }
        
        public System.Threading.Tasks.Task<ApliciacionInventario.ProxyHangar.HangarBE> ConsultarHangarAsync(short id) {
            return base.Channel.ConsultarHangarAsync(id);
        }
        
        public ApliciacionInventario.ProxyHangar.HangarBE ConsultarHangar2(short id) {
            return base.Channel.ConsultarHangar2(id);
        }
        
        public System.Threading.Tasks.Task<ApliciacionInventario.ProxyHangar.HangarBE> ConsultarHangar2Async(short id) {
            return base.Channel.ConsultarHangar2Async(id);
        }
        
        public ApliciacionInventario.ProxyHangar.HangarBE[] ListarHangar() {
            return base.Channel.ListarHangar();
        }
        
        public System.Threading.Tasks.Task<ApliciacionInventario.ProxyHangar.HangarBE[]> ListarHangarAsync() {
            return base.Channel.ListarHangarAsync();
        }
        
        public ApliciacionInventario.ProxyHangar.HangarBE[] ListarHangar2() {
            return base.Channel.ListarHangar2();
        }
        
        public System.Threading.Tasks.Task<ApliciacionInventario.ProxyHangar.HangarBE[]> ListarHangar2Async() {
            return base.Channel.ListarHangar2Async();
        }
        
        public bool InsertarHangar(ApliciacionInventario.ProxyHangar.HangarBE objHangarBE) {
            return base.Channel.InsertarHangar(objHangarBE);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarHangarAsync(ApliciacionInventario.ProxyHangar.HangarBE objHangarBE) {
            return base.Channel.InsertarHangarAsync(objHangarBE);
        }
        
        public bool ActualizarHangar(ApliciacionInventario.ProxyHangar.HangarBE objHangarBE) {
            return base.Channel.ActualizarHangar(objHangarBE);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarHangarAsync(ApliciacionInventario.ProxyHangar.HangarBE objHangarBE) {
            return base.Channel.ActualizarHangarAsync(objHangarBE);
        }
        
        public bool EliminarHangar(short id) {
            return base.Channel.EliminarHangar(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarHangarAsync(short id) {
            return base.Channel.EliminarHangarAsync(id);
        }
    }
}
