//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Inventario
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AltelizaActivosEntities : DbContext
    {
        public AltelizaActivosEntities()
            : base("name=AltelizaActivosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_ATO> TB_ATO { get; set; }
        public virtual DbSet<TB_Hangar> TB_Hangar { get; set; }
        public virtual DbSet<Tb_modelosLucesE> Tb_modelosLucesE { get; set; }
        public virtual DbSet<TB_PlazaLat> TB_PlazaLat { get; set; }
        public virtual DbSet<Tb_Usuario> Tb_Usuario { get; set; }
        public virtual DbSet<TB_ATOAud> TB_ATOAud { get; set; }
        public virtual DbSet<TB_HangarAud> TB_HangarAud { get; set; }
        public virtual DbSet<Tb_modelosLucesE_Aud> Tb_modelosLucesE_Aud { get; set; }
        public virtual DbSet<TB_PlazaLatAud> TB_PlazaLatAud { get; set; }
    
        public virtual int spu_ActualizarATO(Nullable<int> vid, Nullable<int> vpiso, string varea, Nullable<int> vequipo, string vestado, string vobs, string vimagen, string vusu_ult_modificacion, Nullable<int> vactivo)
        {
            var vidParameter = vid.HasValue ?
                new ObjectParameter("vid", vid) :
                new ObjectParameter("vid", typeof(int));
    
            var vpisoParameter = vpiso.HasValue ?
                new ObjectParameter("vpiso", vpiso) :
                new ObjectParameter("vpiso", typeof(int));
    
            var vareaParameter = varea != null ?
                new ObjectParameter("varea", varea) :
                new ObjectParameter("varea", typeof(string));
    
            var vequipoParameter = vequipo.HasValue ?
                new ObjectParameter("vequipo", vequipo) :
                new ObjectParameter("vequipo", typeof(int));
    
            var vestadoParameter = vestado != null ?
                new ObjectParameter("vestado", vestado) :
                new ObjectParameter("vestado", typeof(string));
    
            var vobsParameter = vobs != null ?
                new ObjectParameter("vobs", vobs) :
                new ObjectParameter("vobs", typeof(string));
    
            var vimagenParameter = vimagen != null ?
                new ObjectParameter("vimagen", vimagen) :
                new ObjectParameter("vimagen", typeof(string));
    
            var vusu_ult_modificacionParameter = vusu_ult_modificacion != null ?
                new ObjectParameter("vusu_ult_modificacion", vusu_ult_modificacion) :
                new ObjectParameter("vusu_ult_modificacion", typeof(string));
    
            var vactivoParameter = vactivo.HasValue ?
                new ObjectParameter("vactivo", vactivo) :
                new ObjectParameter("vactivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spu_ActualizarATO", vidParameter, vpisoParameter, vareaParameter, vequipoParameter, vestadoParameter, vobsParameter, vimagenParameter, vusu_ult_modificacionParameter, vactivoParameter);
        }
    
        public virtual int spu_ActualizarHangar(Nullable<int> vid, Nullable<int> vpiso, string varea, Nullable<int> vequipo, string vestado, string vobs, string vimagen, string vusu_ult_modificacion, Nullable<int> vactivo)
        {
            var vidParameter = vid.HasValue ?
                new ObjectParameter("vid", vid) :
                new ObjectParameter("vid", typeof(int));
    
            var vpisoParameter = vpiso.HasValue ?
                new ObjectParameter("vpiso", vpiso) :
                new ObjectParameter("vpiso", typeof(int));
    
            var vareaParameter = varea != null ?
                new ObjectParameter("varea", varea) :
                new ObjectParameter("varea", typeof(string));
    
            var vequipoParameter = vequipo.HasValue ?
                new ObjectParameter("vequipo", vequipo) :
                new ObjectParameter("vequipo", typeof(int));
    
            var vestadoParameter = vestado != null ?
                new ObjectParameter("vestado", vestado) :
                new ObjectParameter("vestado", typeof(string));
    
            var vobsParameter = vobs != null ?
                new ObjectParameter("vobs", vobs) :
                new ObjectParameter("vobs", typeof(string));
    
            var vimagenParameter = vimagen != null ?
                new ObjectParameter("vimagen", vimagen) :
                new ObjectParameter("vimagen", typeof(string));
    
            var vusu_ult_modificacionParameter = vusu_ult_modificacion != null ?
                new ObjectParameter("vusu_ult_modificacion", vusu_ult_modificacion) :
                new ObjectParameter("vusu_ult_modificacion", typeof(string));
    
            var vactivoParameter = vactivo.HasValue ?
                new ObjectParameter("vactivo", vactivo) :
                new ObjectParameter("vactivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spu_ActualizarHangar", vidParameter, vpisoParameter, vareaParameter, vequipoParameter, vestadoParameter, vobsParameter, vimagenParameter, vusu_ult_modificacionParameter, vactivoParameter);
        }
    
        public virtual int spu_ActualizarModelo(Nullable<int> vid, string vmarca, string vmodelo, string vtipo, string vusu_ult_modificacion)
        {
            var vidParameter = vid.HasValue ?
                new ObjectParameter("vid", vid) :
                new ObjectParameter("vid", typeof(int));
    
            var vmarcaParameter = vmarca != null ?
                new ObjectParameter("vmarca", vmarca) :
                new ObjectParameter("vmarca", typeof(string));
    
            var vmodeloParameter = vmodelo != null ?
                new ObjectParameter("vmodelo", vmodelo) :
                new ObjectParameter("vmodelo", typeof(string));
    
            var vtipoParameter = vtipo != null ?
                new ObjectParameter("vtipo", vtipo) :
                new ObjectParameter("vtipo", typeof(string));
    
            var vusu_ult_modificacionParameter = vusu_ult_modificacion != null ?
                new ObjectParameter("vusu_ult_modificacion", vusu_ult_modificacion) :
                new ObjectParameter("vusu_ult_modificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spu_ActualizarModelo", vidParameter, vmarcaParameter, vmodeloParameter, vtipoParameter, vusu_ult_modificacionParameter);
        }
    
        public virtual int spu_ActualizarPlazaLat(Nullable<int> vid, Nullable<int> vpiso, string varea, Nullable<int> vequipo, string vestado, string vobs, string vimagen, string vusu_ult_modificacion, Nullable<int> vactivo)
        {
            var vidParameter = vid.HasValue ?
                new ObjectParameter("vid", vid) :
                new ObjectParameter("vid", typeof(int));
    
            var vpisoParameter = vpiso.HasValue ?
                new ObjectParameter("vpiso", vpiso) :
                new ObjectParameter("vpiso", typeof(int));
    
            var vareaParameter = varea != null ?
                new ObjectParameter("varea", varea) :
                new ObjectParameter("varea", typeof(string));
    
            var vequipoParameter = vequipo.HasValue ?
                new ObjectParameter("vequipo", vequipo) :
                new ObjectParameter("vequipo", typeof(int));
    
            var vestadoParameter = vestado != null ?
                new ObjectParameter("vestado", vestado) :
                new ObjectParameter("vestado", typeof(string));
    
            var vobsParameter = vobs != null ?
                new ObjectParameter("vobs", vobs) :
                new ObjectParameter("vobs", typeof(string));
    
            var vimagenParameter = vimagen != null ?
                new ObjectParameter("vimagen", vimagen) :
                new ObjectParameter("vimagen", typeof(string));
    
            var vusu_ult_modificacionParameter = vusu_ult_modificacion != null ?
                new ObjectParameter("vusu_ult_modificacion", vusu_ult_modificacion) :
                new ObjectParameter("vusu_ult_modificacion", typeof(string));
    
            var vactivoParameter = vactivo.HasValue ?
                new ObjectParameter("vactivo", vactivo) :
                new ObjectParameter("vactivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spu_ActualizarPlazaLat", vidParameter, vpisoParameter, vareaParameter, vequipoParameter, vestadoParameter, vobsParameter, vimagenParameter, vusu_ult_modificacionParameter, vactivoParameter);
        }
    
        public virtual ObjectResult<spu_ConsultarATO_Result> spu_ConsultarATO(Nullable<int> vid)
        {
            var vidParameter = vid.HasValue ?
                new ObjectParameter("vid", vid) :
                new ObjectParameter("vid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spu_ConsultarATO_Result>("spu_ConsultarATO", vidParameter);
        }
    
        public virtual ObjectResult<spu_ConsultarATO2_Result> spu_ConsultarATO2(Nullable<int> vid)
        {
            var vidParameter = vid.HasValue ?
                new ObjectParameter("vid", vid) :
                new ObjectParameter("vid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spu_ConsultarATO2_Result>("spu_ConsultarATO2", vidParameter);
        }
    
        public virtual ObjectResult<spu_ConsultarHangar_Result> spu_ConsultarHangar(Nullable<int> vid)
        {
            var vidParameter = vid.HasValue ?
                new ObjectParameter("vid", vid) :
                new ObjectParameter("vid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spu_ConsultarHangar_Result>("spu_ConsultarHangar", vidParameter);
        }
    
        public virtual ObjectResult<spu_ConsultarHangar2_Result> spu_ConsultarHangar2(Nullable<int> vid)
        {
            var vidParameter = vid.HasValue ?
                new ObjectParameter("vid", vid) :
                new ObjectParameter("vid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spu_ConsultarHangar2_Result>("spu_ConsultarHangar2", vidParameter);
        }
    
        public virtual ObjectResult<spu_ConsultarModelo_Result> spu_ConsultarModelo(Nullable<int> vid)
        {
            var vidParameter = vid.HasValue ?
                new ObjectParameter("vid", vid) :
                new ObjectParameter("vid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spu_ConsultarModelo_Result>("spu_ConsultarModelo", vidParameter);
        }
    
        public virtual ObjectResult<spu_ConsultarPlazaLat_Result> spu_ConsultarPlazaLat(Nullable<int> vid)
        {
            var vidParameter = vid.HasValue ?
                new ObjectParameter("vid", vid) :
                new ObjectParameter("vid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spu_ConsultarPlazaLat_Result>("spu_ConsultarPlazaLat", vidParameter);
        }
    
        public virtual ObjectResult<spu_ConsultarPlazaLat2_Result> spu_ConsultarPlazaLat2(Nullable<int> vid)
        {
            var vidParameter = vid.HasValue ?
                new ObjectParameter("vid", vid) :
                new ObjectParameter("vid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spu_ConsultarPlazaLat2_Result>("spu_ConsultarPlazaLat2", vidParameter);
        }
    
        public virtual int spu_EliminarATO(Nullable<int> vid)
        {
            var vidParameter = vid.HasValue ?
                new ObjectParameter("vid", vid) :
                new ObjectParameter("vid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spu_EliminarATO", vidParameter);
        }
    
        public virtual int spu_EliminarHangar(Nullable<int> vid)
        {
            var vidParameter = vid.HasValue ?
                new ObjectParameter("vid", vid) :
                new ObjectParameter("vid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spu_EliminarHangar", vidParameter);
        }
    
        public virtual int spu_EliminarModelo(Nullable<int> vid)
        {
            var vidParameter = vid.HasValue ?
                new ObjectParameter("vid", vid) :
                new ObjectParameter("vid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spu_EliminarModelo", vidParameter);
        }
    
        public virtual int spu_EliminarPlazaLat(Nullable<int> vid)
        {
            var vidParameter = vid.HasValue ?
                new ObjectParameter("vid", vid) :
                new ObjectParameter("vid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spu_EliminarPlazaLat", vidParameter);
        }
    
        public virtual int spu_InsertarATO(Nullable<int> vpiso, string varea, Nullable<int> vequipo, string vestado, string vobs, string vimagen, string vusu_registro, Nullable<int> vactivo)
        {
            var vpisoParameter = vpiso.HasValue ?
                new ObjectParameter("vpiso", vpiso) :
                new ObjectParameter("vpiso", typeof(int));
    
            var vareaParameter = varea != null ?
                new ObjectParameter("varea", varea) :
                new ObjectParameter("varea", typeof(string));
    
            var vequipoParameter = vequipo.HasValue ?
                new ObjectParameter("vequipo", vequipo) :
                new ObjectParameter("vequipo", typeof(int));
    
            var vestadoParameter = vestado != null ?
                new ObjectParameter("vestado", vestado) :
                new ObjectParameter("vestado", typeof(string));
    
            var vobsParameter = vobs != null ?
                new ObjectParameter("vobs", vobs) :
                new ObjectParameter("vobs", typeof(string));
    
            var vimagenParameter = vimagen != null ?
                new ObjectParameter("vimagen", vimagen) :
                new ObjectParameter("vimagen", typeof(string));
    
            var vusu_registroParameter = vusu_registro != null ?
                new ObjectParameter("vusu_registro", vusu_registro) :
                new ObjectParameter("vusu_registro", typeof(string));
    
            var vactivoParameter = vactivo.HasValue ?
                new ObjectParameter("vactivo", vactivo) :
                new ObjectParameter("vactivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spu_InsertarATO", vpisoParameter, vareaParameter, vequipoParameter, vestadoParameter, vobsParameter, vimagenParameter, vusu_registroParameter, vactivoParameter);
        }
    
        public virtual int spu_InsertarHangar(Nullable<int> vpiso, string varea, Nullable<int> vequipo, string vestado, string vobs, string vimagen, string vusu_registro, Nullable<int> vactivo)
        {
            var vpisoParameter = vpiso.HasValue ?
                new ObjectParameter("vpiso", vpiso) :
                new ObjectParameter("vpiso", typeof(int));
    
            var vareaParameter = varea != null ?
                new ObjectParameter("varea", varea) :
                new ObjectParameter("varea", typeof(string));
    
            var vequipoParameter = vequipo.HasValue ?
                new ObjectParameter("vequipo", vequipo) :
                new ObjectParameter("vequipo", typeof(int));
    
            var vestadoParameter = vestado != null ?
                new ObjectParameter("vestado", vestado) :
                new ObjectParameter("vestado", typeof(string));
    
            var vobsParameter = vobs != null ?
                new ObjectParameter("vobs", vobs) :
                new ObjectParameter("vobs", typeof(string));
    
            var vimagenParameter = vimagen != null ?
                new ObjectParameter("vimagen", vimagen) :
                new ObjectParameter("vimagen", typeof(string));
    
            var vusu_registroParameter = vusu_registro != null ?
                new ObjectParameter("vusu_registro", vusu_registro) :
                new ObjectParameter("vusu_registro", typeof(string));
    
            var vactivoParameter = vactivo.HasValue ?
                new ObjectParameter("vactivo", vactivo) :
                new ObjectParameter("vactivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spu_InsertarHangar", vpisoParameter, vareaParameter, vequipoParameter, vestadoParameter, vobsParameter, vimagenParameter, vusu_registroParameter, vactivoParameter);
        }
    
        public virtual int spu_InsertarModelo(string vmarca, string vmodelo, string vtipo, string vusu_registro)
        {
            var vmarcaParameter = vmarca != null ?
                new ObjectParameter("vmarca", vmarca) :
                new ObjectParameter("vmarca", typeof(string));
    
            var vmodeloParameter = vmodelo != null ?
                new ObjectParameter("vmodelo", vmodelo) :
                new ObjectParameter("vmodelo", typeof(string));
    
            var vtipoParameter = vtipo != null ?
                new ObjectParameter("vtipo", vtipo) :
                new ObjectParameter("vtipo", typeof(string));
    
            var vusu_registroParameter = vusu_registro != null ?
                new ObjectParameter("vusu_registro", vusu_registro) :
                new ObjectParameter("vusu_registro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spu_InsertarModelo", vmarcaParameter, vmodeloParameter, vtipoParameter, vusu_registroParameter);
        }
    
        public virtual int spu_InsertarPlazaLat(Nullable<int> vpiso, string varea, Nullable<int> vequipo, string vestado, string vobs, string vimagen, string vusu_registro, Nullable<int> vactivo)
        {
            var vpisoParameter = vpiso.HasValue ?
                new ObjectParameter("vpiso", vpiso) :
                new ObjectParameter("vpiso", typeof(int));
    
            var vareaParameter = varea != null ?
                new ObjectParameter("varea", varea) :
                new ObjectParameter("varea", typeof(string));
    
            var vequipoParameter = vequipo.HasValue ?
                new ObjectParameter("vequipo", vequipo) :
                new ObjectParameter("vequipo", typeof(int));
    
            var vestadoParameter = vestado != null ?
                new ObjectParameter("vestado", vestado) :
                new ObjectParameter("vestado", typeof(string));
    
            var vobsParameter = vobs != null ?
                new ObjectParameter("vobs", vobs) :
                new ObjectParameter("vobs", typeof(string));
    
            var vimagenParameter = vimagen != null ?
                new ObjectParameter("vimagen", vimagen) :
                new ObjectParameter("vimagen", typeof(string));
    
            var vusu_registroParameter = vusu_registro != null ?
                new ObjectParameter("vusu_registro", vusu_registro) :
                new ObjectParameter("vusu_registro", typeof(string));
    
            var vactivoParameter = vactivo.HasValue ?
                new ObjectParameter("vactivo", vactivo) :
                new ObjectParameter("vactivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spu_InsertarPlazaLat", vpisoParameter, vareaParameter, vequipoParameter, vestadoParameter, vobsParameter, vimagenParameter, vusu_registroParameter, vactivoParameter);
        }
    
        public virtual int spu_InsertarUsuario(string vlog_usu, string vpass, Nullable<int> vniv, Nullable<int> vest, string vusu_registro)
        {
            var vlog_usuParameter = vlog_usu != null ?
                new ObjectParameter("vlog_usu", vlog_usu) :
                new ObjectParameter("vlog_usu", typeof(string));
    
            var vpassParameter = vpass != null ?
                new ObjectParameter("vpass", vpass) :
                new ObjectParameter("vpass", typeof(string));
    
            var vnivParameter = vniv.HasValue ?
                new ObjectParameter("vniv", vniv) :
                new ObjectParameter("vniv", typeof(int));
    
            var vestParameter = vest.HasValue ?
                new ObjectParameter("vest", vest) :
                new ObjectParameter("vest", typeof(int));
    
            var vusu_registroParameter = vusu_registro != null ?
                new ObjectParameter("vusu_registro", vusu_registro) :
                new ObjectParameter("vusu_registro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spu_InsertarUsuario", vlog_usuParameter, vpassParameter, vnivParameter, vestParameter, vusu_registroParameter);
        }
    
        public virtual ObjectResult<spu_ListarATO_Result> spu_ListarATO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spu_ListarATO_Result>("spu_ListarATO");
        }
    
        public virtual ObjectResult<spu_ListarATO2_Result> spu_ListarATO2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spu_ListarATO2_Result>("spu_ListarATO2");
        }
    
        public virtual ObjectResult<spu_ListarHangar_Result> spu_ListarHangar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spu_ListarHangar_Result>("spu_ListarHangar");
        }
    
        public virtual ObjectResult<spu_ListarHangar2_Result> spu_ListarHangar2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spu_ListarHangar2_Result>("spu_ListarHangar2");
        }
    
        public virtual ObjectResult<spu_ListarModelo_Result> spu_ListarModelo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spu_ListarModelo_Result>("spu_ListarModelo");
        }
    
        public virtual ObjectResult<spu_ListarPlazaLat_Result> spu_ListarPlazaLat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spu_ListarPlazaLat_Result>("spu_ListarPlazaLat");
        }
    
        public virtual ObjectResult<spu_ListarPlazaLat2_Result> spu_ListarPlazaLat2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spu_ListarPlazaLat2_Result>("spu_ListarPlazaLat2");
        }
    
        public virtual ObjectResult<usp_ConsultarUsuario_Result> usp_ConsultarUsuario(string login_Usuario)
        {
            var login_UsuarioParameter = login_Usuario != null ?
                new ObjectParameter("Login_Usuario", login_Usuario) :
                new ObjectParameter("Login_Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarUsuario_Result>("usp_ConsultarUsuario", login_UsuarioParameter);
        }
    
        public virtual ObjectResult<spu_ListarModelo2_Result> spu_ListarModelo2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spu_ListarModelo2_Result>("spu_ListarModelo2");
        }
    }
}
