//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HangarAud
    {
        public Nullable<int> id { get; set; }
        public int piso { get; set; }
        public string area { get; set; }
        public int equipo { get; set; }
        public string estado { get; set; }
        public string obs { get; set; }
        public string imagen { get; set; }
        public string usuario_registro { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string usu_ult_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_ult_modificacion { get; set; }
        public Nullable<int> activo { get; set; }
        public string accion { get; set; }
        public Nullable<System.DateTime> fec_accion { get; set; }
    }
}
