//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Inventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_modelosLucesE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_modelosLucesE()
        {
            this.TB_ATO = new HashSet<TB_ATO>();
            this.TB_Hangar = new HashSet<TB_Hangar>();
            this.TB_PlazaLat = new HashSet<TB_PlazaLat>();
        }
    
        public int id { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string tipo { get; set; }
        public string usuario_registro { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string usu_ult_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_ult_modificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ATO> TB_ATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Hangar> TB_Hangar { get; set; }
        public virtual Tb_Usuario Tb_Usuario { get; set; }
        public virtual Tb_Usuario Tb_Usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PlazaLat> TB_PlazaLat { get; set; }
    }
}
