//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApliciacionInventario.ProxyUsuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Inventario")]
    [System.SerializableAttribute()]
    public partial class UsuarioBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short est_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string login_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short niv_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pass_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usu_registroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Registro {
            get {
                return this.Fec_RegistroField;
            }
            set {
                if ((this.Fec_RegistroField.Equals(value) != true)) {
                    this.Fec_RegistroField = value;
                    this.RaisePropertyChanged("Fec_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short est_usuario {
            get {
                return this.est_usuarioField;
            }
            set {
                if ((this.est_usuarioField.Equals(value) != true)) {
                    this.est_usuarioField = value;
                    this.RaisePropertyChanged("est_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login_usuario {
            get {
                return this.login_usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.login_usuarioField, value) != true)) {
                    this.login_usuarioField = value;
                    this.RaisePropertyChanged("login_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short niv_usuario {
            get {
                return this.niv_usuarioField;
            }
            set {
                if ((this.niv_usuarioField.Equals(value) != true)) {
                    this.niv_usuarioField = value;
                    this.RaisePropertyChanged("niv_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pass_usuario {
            get {
                return this.pass_usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.pass_usuarioField, value) != true)) {
                    this.pass_usuarioField = value;
                    this.RaisePropertyChanged("pass_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usu_registro {
            get {
                return this.usu_registroField;
            }
            set {
                if ((object.ReferenceEquals(this.usu_registroField, value) != true)) {
                    this.usu_registroField = value;
                    this.RaisePropertyChanged("usu_registro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyUsuario.IServiceUsuario")]
    public interface IServiceUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/InsertarUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/InsertarUsuarioResponse")]
        bool InsertarUsuario(ApliciacionInventario.ProxyUsuario.UsuarioBE objUsuarioBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/InsertarUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/InsertarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> InsertarUsuarioAsync(ApliciacionInventario.ProxyUsuario.UsuarioBE objUsuarioBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/ActualizarUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/ActualizarUsuarioResponse")]
        bool ActualizarUsuario(ApliciacionInventario.ProxyUsuario.UsuarioBE objUsuarioBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/ActualizarUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/ActualizarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> ActualizarUsuarioAsync(ApliciacionInventario.ProxyUsuario.UsuarioBE objUsuarioBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/EliminarUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/EliminarUsuarioResponse")]
        bool EliminarUsuario(string login_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/EliminarUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> EliminarUsuarioAsync(string login_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/ConsultarUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/ConsultarUsuarioResponse")]
        ApliciacionInventario.ProxyUsuario.UsuarioBE ConsultarUsuario(string login_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceUsuario/ConsultarUsuario", ReplyAction="http://tempuri.org/IServiceUsuario/ConsultarUsuarioResponse")]
        System.Threading.Tasks.Task<ApliciacionInventario.ProxyUsuario.UsuarioBE> ConsultarUsuarioAsync(string login_usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceUsuarioChannel : ApliciacionInventario.ProxyUsuario.IServiceUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceUsuarioClient : System.ServiceModel.ClientBase<ApliciacionInventario.ProxyUsuario.IServiceUsuario>, ApliciacionInventario.ProxyUsuario.IServiceUsuario {
        
        public ServiceUsuarioClient() {
        }
        
        public ServiceUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertarUsuario(ApliciacionInventario.ProxyUsuario.UsuarioBE objUsuarioBE) {
            return base.Channel.InsertarUsuario(objUsuarioBE);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarUsuarioAsync(ApliciacionInventario.ProxyUsuario.UsuarioBE objUsuarioBE) {
            return base.Channel.InsertarUsuarioAsync(objUsuarioBE);
        }
        
        public bool ActualizarUsuario(ApliciacionInventario.ProxyUsuario.UsuarioBE objUsuarioBE) {
            return base.Channel.ActualizarUsuario(objUsuarioBE);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarUsuarioAsync(ApliciacionInventario.ProxyUsuario.UsuarioBE objUsuarioBE) {
            return base.Channel.ActualizarUsuarioAsync(objUsuarioBE);
        }
        
        public bool EliminarUsuario(string login_usuario) {
            return base.Channel.EliminarUsuario(login_usuario);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarUsuarioAsync(string login_usuario) {
            return base.Channel.EliminarUsuarioAsync(login_usuario);
        }
        
        public ApliciacionInventario.ProxyUsuario.UsuarioBE ConsultarUsuario(string login_usuario) {
            return base.Channel.ConsultarUsuario(login_usuario);
        }
        
        public System.Threading.Tasks.Task<ApliciacionInventario.ProxyUsuario.UsuarioBE> ConsultarUsuarioAsync(string login_usuario) {
            return base.Channel.ConsultarUsuarioAsync(login_usuario);
        }
    }
}
